project_id = "bgqlhaqwsnfhhatxhtfx"

[functions.send-password-reset]
verify_jwt = false

[functions.reset-link-gateway]
verify_jwt = false

[functions.generate-admin-reset-link]
verify_jwt = true

[functions.admin-impersonate]
verify_jwt = true

[functions.admin-impersonate-end]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-subscription-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
